# ===========================
# Stage 1 - Build the project
# ===========================
FROM maven:3.9.9-eclipse-temurin-17 AS build

WORKDIR /app

# Copy pom.xml first
COPY pom.xml .

# Download dependencies
RUN mvn dependency:go-offline

# Copy source code
COPY src ./src

# Build the application
RUN mvn clean package -DskipTests


# ===========================
# Stage 2 - Run the application
# ===========================
FROM eclipse-temurin:17-jdk

WORKDIR /app

# Copy the generated jar
COPY --from=build /app/target/*.jar app.jar

# Render provides PORT automatically
EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]