spring.application.name=spare-parts-inventory
server.port=8080
server.servlet.context-path=/api

# JWT
jwt.secret=qSt1VBtVDX72xPYetFyExyMt2jp9ybihP5QIBugNrCv
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.spareparts=DEBUG
logging.level.org.springframework.security=INFO

# Profile
spring.profiles.active=mysql

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Disable whitelabel error page
server.error.whitelabel.enabled=false
spring.web.resources.add-mappings=false
